# Book settings
title: Coastal Processes, Environments and Systems
author: Tristan Salles
logo: _static/cp-logo-large.png
description: These lectures provides a short introduction to coastal systems analysis using both ocean data and numerical models, designed and written by Tristan Salles.

sphinx:
    config:
        html_theme: quantecon_book_theme
        html_theme_options:
            header_organisation_url: https://www.sydney.edu.au/units
            header_organisation: CoastProc
            repository_url: https://github.com/tristan-salles/CoastProc-book
            nb_repository_url: https://github.com/tristan-salles/CoastProc-notebooks
            twitter: salles_tristan
            twitter_logo_url: https://iili.io/H7sltov.md.png
            og_logo_url: https://iili.io/H7sltov.th.png
            description: These lectures provides a short introduction to coastal systems analysis using both ocean data and numerical models, designed and written by Tristan Salles.
            keywords: Python, Coastal Change, USYD, Wave Analysis, Geoscience Data
            # google_analytics_id: UA-54984338-10
        bibtex_reference_style: author_year
        mathjax3_config:
            tex:
                macros:
                    "Exp" : "\\operatorname{Exp}"
                    "Binomial" : "\\operatorname{Binomial}"
                    "Poisson" : "\\operatorname{Poisson}"
                    "BB" : "\\mathbb{B}"
                    "EE" : "\\mathbb{E}"
                    "PP" : "\\mathbb{P}"
                    "RR" : "\\mathbb{R}"
                    "NN" : "\\mathbb{N}"
                    "ZZ" : "\\mathbb{Z}"
                    "dD" : "\\mathcal{D}"
                    "fF" : "\\mathcal{F}"
                    "lL" : "\\mathcal{L}"
                    "linop" : "\\mathcal{L}(\\mathbb{B})"
                    "linopell" : "\\mathcal{L}(\\ell_1)"

    extra_extensions:
        - sphinx_proof
        - sphinx_exercise
        - sphinx_tojupyter

execute:
    execute_notebooks: cache

latex:
    latex_engine: "xelatex"
    latex_documents:
        targetname: book.tex

bibtex_bibfiles:
    - references.bib
